name: Run kotlin-project-jitpack

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]
        java: [ '11', '17' ]
        distribution: [ 'temurin' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Print dependency tree
        run: cd ./kotlin-project-jitpack && ./gradlew app:dependencies
      - name: Build with Gradle
        run: cd ./kotlin-project-jitpack && ./gradlew build
      - name: Run the project
        run: cd ./kotlin-project-jitpack && ./gradlew run --args="${PWD}/../datasets/Town01.xodr"
