name: Run kts-scripts-jitpack

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]
        java: [ '11', '16', '17' ]
        distribution: [ 'temurin' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Install sdkman
        run: curl -s "https://get.sdkman.io" | bash
      - name: Install kotlin
        run: (source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install kotlin)
      - name: Install kscript
        run: (source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install kscript)
      - name: Run convert-opendrive-to-citygml2.kts
        run: (source "$HOME/.sdkman/bin/sdkman-init.sh" && cd ./kts-scripts-jitpack && kscript ./convert-opendrive-to-citygml2.kts)
      - name: Run convert-opendrive-to-citygml3.kts
        run: (source "$HOME/.sdkman/bin/sdkman-init.sh" && cd ./kts-scripts-jitpack && kscript ./convert-opendrive-to-citygml3.kts)
